/**
 * j_com_mycompany_myapp_MyViewController.h
 *
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * It is used to provide Java class visibility to IntefaceBuilder
 * DO NOT MODIFY! DO NOT ADD UNDER VERSION CONTROL
 */

@interface j_com_mycompany_myapp_MyViewController : UIViewController

@end
